

// Best to avoid choices redundant with those offered by Nuclide.
// Not sure if EXPLOSION and SHAKE are already provided.
enum EVENT_TS{
	SPAWN = EV_SEPARATOR,
	RESET_VIEW_MODEL,
	RESET_PLAYER,
	PLAYER_DEATH,
	PLAYER_NOCLIP,
	EV_IMPACT_MELEE,
	//DROP_WEAPON,
	FX_TS_EXPLOSION_GRENADE,
	EQUIP_CALLBACK,
	TEST_CALLBACK,
	SOUNDPITCHED,
	SOUNDPITCHED_CHANNEL,
	USEITEMS_CHANGE_CALLBACK,
	
	CUSTOM_PREDICTION_CALLBACK,
	
	VIEWANGLES_REQUEST,

	TEST,
};

