

void SoundPitched_Send(entity ent, int id);
void SoundPitched_Channel_Send(entity ent, int id, float chan);

#ifdef CLIENT
void SoundPitched_Receive(void);
void SoundPitched_Channel_Receive(void);
#endif



typedef enum
{
	SNDP_AK47_FIRE,
	SNDP_AKIMBOCOLTS_FIRE,
	SNDP_BARRETTM82_FIRE,
	SNDP_BENELLIM3_FIRE,
	SNDP_BERETTA_FIRE,
	SNDP_BERETTA_FIRE_SIL,
	SNDP_CONTENDERG2_FIRE,
	SNDP_DESERTEAGLE_FIRE,
	SNDP_DESERTEAGLE_FIRE_SIL,
	SNDP_FIVESEVEN_FIRE,
	SNDP_FIVESEVEN_FIRE_SIL,
	SNDP_GLOCK18_FIRE,
	SNDP_GLOCK18_FIRE_SIL,
	SNDP_GLOCK20_FIRE,
	SNDP_GLOCK20_FIRE_SIL,
	SNDP_HKPDW_FIRE,
	SNDP_HKPDW_FIRE_SIL,
	SNDP_KATANA_MISS,
	SNDP_KATANA_MISS1,
	SNDP_M4A1_FIRE,
	SNDP_M4A1_FIRE_SIL,
	SNDP_M16A4_FIRE,
	SNDP_M60_FIRE,
	SNDP_MAC10_FIRE,
	SNDP_MAC10_FIRE_SIL,
	SNDP_MINIUZI_FIRE,
	SNDP_MINIUZI_FIRE_SIL,
	SNDP_MOSSBERG500_FIRE,
	SNDP_MP5K_FIRE,
	SNDP_MP5K_FIRE_SIL,
	SNDP_MP5SD_FIRE,
	SNDP_RAGINGBULL_FIRE,
	SNDP_RUGERMK1_FIRE,
	SNDP_SAWEDOFF_FIRE,
	SNDP_SKORPION_FIRE,
	SNDP_SOCOMMK23_FIRE,
	SNDP_SOCOMMK23_FIRE_SIL,
	SNDP_SPAS12_FIRE,
	SNDP_STEYRAUG_FIRE,
	SNDP_STEYRAUG_FIRE_SIL,
	SNDP_STEYRTMP_FIRE,
	SNDP_STEYRTMP_FIRE_SIL,
	SNDP_UMP_FIRE,
	SNDP_UMP_FIRE_SIL,
	SNDP_USAS12_FIRE,
	SNDP_EXPLODE,
	SNDP_EXPLODE1,
	SNDP_EXPLODE2,
	SNDP_EXPLODE3,
	SNDP_EXPLODE4
	
} sfx_pitched_t;
