#define CG_OWNERDRAW_BASE           1
#define CG_PLAYER_ARMOR_ICON        1
#define CG_PLAYER_ARMOR_VALUE       2
#define CG_PLAYER_HEAD              3
#define CG_PLAYER_HEALTH            4
#define CG_PLAYER_AMMO_ICON         5
#define CG_PLAYER_AMMO_VALUE        6
#define CG_SELECTEDPLAYER_HEAD      7
#define CG_SELECTEDPLAYER_NAME      8
#define CG_SELECTEDPLAYER_LOCATION  9
#define CG_SELECTEDPLAYER_STATUS    10
#define CG_SELECTEDPLAYER_WEAPON    11
#define CG_SELECTEDPLAYER_POWERUP   12
#define CG_FLAGCARRIER_HEAD         13
#define CG_FLAGCARRIER_NAME         14
#define CG_FLAGCARRIER_LOCATION     15
#define CG_FLAGCARRIER_STATUS       16
#define CG_FLAGCARRIER_WEAPON       17
#define CG_FLAGCARRIER_POWERUP      18
#define CG_PLAYER_ITEM              19
#define CG_PLAYER_SCORE             20
#define CG_BLUE_FLAGHEAD            21
#define CG_BLUE_FLAGSTATUS          22
#define CG_BLUE_FLAGNAME            23
#define CG_RED_FLAGHEAD             24
#define CG_RED_FLAGSTATUS           25
#define CG_RED_FLAGNAME             26
#define CG_BLUE_SCORE               27
#define CG_RED_SCORE                28
#define CG_RED_NAME                 29
#define CG_BLUE_NAME                30
#define CG_HARVESTER_SKULLS         31
#define CG_ONEFLAG_STATUS           32
#define CG_PLAYER_LOCATION          33
#define CG_TEAM_COLOR               34
#define CG_CTF_POWERUP              35
#define CG_AREA_POWERUP             36
#define CG_AREA_LAGOMETER           37
#define CG_PLAYER_HASFLAG           38
#define CG_GAME_TYPE                39
#define CG_SELECTEDPLAYER_ARMOR     40
#define CG_SELECTEDPLAYER_HEALTH    41
#define CG_PLAYER_STATUS            42
#define CG_FRAGGED_MSG              43
#define CG_PROXMINED_MSG            44
#define CG_AREA_FPSINFO             45
#define CG_AREA_SYSTEMCHAT          46
#define CG_AREA_TEAMCHAT            47
#define CG_AREA_CHAT                48
#define CG_GAME_STATUS              49
#define CG_KILLER                   50
#define CG_PLAYER_ARMOR_ICON2D      51
#define CG_PLAYER_AMMO_ICON2D       52
#define CG_ACCURACY                 53
#define CG_ASSISTS                  54
#define CG_DEFEND                   55
#define CG_EXCELLENT                56
#define CG_IMPRESSIVE               57
#define CG_PERFECT                  58
#define CG_GAUNTLET                 59
#define CG_SPECTATORS               60
#define CG_TEAMINFO                 61
#define CG_VOICE_HEAD               62
#define CG_VOICE_NAME               63
#define CG_PLAYER_HASFLAG2D         64
#define CG_HARVESTER_SKULLS2D       65
#define CG_CAPFRAGLIMIT             66
#define CG_1STPLACE                 67
#define CG_2NDPLACE                 68
#define CG_CAPTURES                 69
#define CG_PLAYER_AMMOCLIP_VALUE    70
#define CG_PLAYER_WEAPON_ICON2D     71
#define CG_CURSORHINT               72
#define CG_PLAYER_STAMINA           73
#define CG_PLAYER_WEAPON_HEAT       74
#define CG_PLAYER_INVENTORY         75
#define CG_PLAYER_HOLDABLE          76
#define CG_PLAYER_INVENTORY         77
#define CG_CURSORHINT_STATUS        78
#define CG_PLAYER_BAR_HEALTH        79
#define CG_MANTLE_HINT              80
#define CG_PLAYER_WEAPON_NAME       81
#define CG_PLAYER_WEAPON_NAME_BACK  82
#define CG_PLAYER_WEAPON_MODE_ICON  83
#define CG_PLAYER_COMPASS           84
#define CG_PLAYER_COMPASS_BACK      85
#define CG_PLAYER_COMPASS_POINTERS  86
#define CG_PLAYER_COMPASS_ACTORS    87
#define CG_PLAYER_COMPASS_FRIENDS   88
#define CG_PLAYER_COMPASS_TANKS     89
#define CG_TANK_BODY_DIR            90
#define CG_TANK_BARREL_DIR          91
#define CG_DEADQUOTE                92
#define CG_DRAW_SHADER              94
#define CG_PLAYER_BAR_HEALTH_BACK   95
#define CG_MISSION_OBJECTIVE_HEADER     96
#define CG_MISSION_OBJECTIVE_LIST       97
#define CG_MISSION_OBJECTIVE_BACKDROP   98
#define CG_PAUSED_MENU_LINE             99
#define CG_OFFHAND_WEAPON_ICON_FRAG     100
#define CG_OFFHAND_WEAPON_ICON_SMOKE    101
#define CG_OFFHAND_WEAPON_AMMO_FRAG     102
#define CG_OFFHAND_WEAPON_AMMO_SMOKE    103
#define CG_OFFHAND_WEAPON_NAME_FRAG     104
#define CG_OFFHAND_WEAPON_NAME_SMOKE    105
#define CG_OFFHAND_WEAPON_SELECT_FRAG   106
#define CG_OFFHAND_WEAPON_SELECT_SMOKE  107
#define CG_SAVING                       108
#define CG_PLAYER_LOW_HEALTH_OVERLAY    109
#define CG_INVALID_CMD_HINT             110
#define CG_NUCLIDE_START                256
#define CG_SYSTEM_TIME_SWATCH           257
#define CG_SYSTEM_TIME_12H              258
#define CG_SYSTEM_TIME_24H              259
